import { DaruWorkOSState } from '../types';

export const INITIAL_STATE: DaruWorkOSState = {
  "todayPursuit": [
    {
      "id": "tp-1",
      "projectId": "p-hamasah-ai",
      "project": "Hamasah Internasional",
      "action": "Meeting owner: Discovery integrasi AI ke website & estimasi kebutuhan",
      "isDone": false
    },
    {
      "id": "tp-2",
      "projectId": "p-umi-elly",
      "project": "Umi Elly LMS",
      "action": "Review platform bareng Umi Elly & input kurikulum serta konten modul",
      "isDone": false
    },
    {
      "id": "tp-3",
      "projectId": "p-pgs-tour",
      "project": "Website PGS Tour",
      "action": "Showcase website PGS Tour yang sudah live di pgstour.vercel.app ke owner",
      "isDone": false
    },
    {
      "id": "tp-4",
      "projectId": "p-ifdony-azharuna",
      "project": "Logo Azharuna",
      "action": "Eksplorasi konsep simbol logo, tipografi & mockup visual",
      "isDone": false
    },
    {
      "id": "tp-5",
      "projectId": "p-umi-atiyah",
      "project": "Umi Atiyah",
      "action": "Follow-up pelunasan Rp200.000 (Kerjaan sudah selesai 100%)",
      "isDone": false
    },
    {
      "id": "tp-6",
      "projectId": "p-komisi-interaksi",
      "project": "Rancangan Komisi Peduli Interaksi (KPI)",
      "action": "Penawaran Rp14jt terkirim - Standby konfirmasi DP untuk kickoff build",
      "isDone": false
    },
    {
      "id": "tp-7",
      "projectId": "p-barber",
      "project": "DreamMecca & Barber Underrated",
      "action": "100% Selesai & Lunas tuntas! (Bebas utang pikiran )",
      "isDone": true
    }
  ],
  "quickStats": {
    "paidClientActive": 2,
    "waitingPaymentKickoff": 4,
    "maintenanceOpen": 1,
    "salesAndProductActive": 4
  },
  "financialReport": {
    "asOfDate": "6 September 2026",
    "totalLiquidBalance": 8306524,
    "modeStatus": "YELLOW MODE - CAUTION",
    "hardFloor": 4000000,
    "financialDebt": 0,
    "projectLiabilityNote": "SEMUA UTANG DELIVERABLE TUNTAS! (Barber POS Lunas Penuh Rp6M & Umi Elly DP Rp3M Kickoff Aktif). Nol liability design!",
    "dropFrom26Aug": 0,
    "dropFrom12Aug": 0,
    "dropPercentageFrom12Aug": 0,
    "accounts": [
      {
        "name": "Mandiri",
        "balance": 6855812,
        "isLatest": true,
        "lastUpdated": "6 Sep 2026 (Live)",
        "type": "bank"
      },
      {
        "name": "Bank Jago",
        "balance": 37257,
        "isLatest": true,
        "lastUpdated": "6 Sep 2026 (Live)",
        "type": "bank"
      },
      {
        "name": "blu by BCA",
        "balance": 17733,
        "isLatest": true,
        "lastUpdated": "6 Sep 2026 (Live)",
        "type": "bank"
      },
      {
        "name": "LINE Bank",
        "balance": 1359836,
        "isLatest": true,
        "lastUpdated": "6 Sep 2026 (Live)",
        "type": "bank"
      },
      {
        "name": "DANA",
        "balance": 27496,
        "isLatest": true,
        "lastUpdated": "6 Sep 2026 (Live)",
        "type": "ewallet"
      },
      {
        "name": "GoPay",
        "balance": 8390,
        "isLatest": true,
        "lastUpdated": "6 Sep 2026 (Live)",
        "type": "ewallet"
      },
      {
        "name": "Cash",
        "balance": 0,
        "isLatest": true,
        "lastUpdated": "6 Sep 2026 (Live)",
        "type": "cash"
      }
    ],
    "trajectory": [
      {
        "date": "12 Agu",
        "balance": 7810773,
        "note": "Peak Balance Agustus"
      },
      {
        "date": "20 Agu",
        "balance": 5885040,
        "note": "-Rp1.92M"
      },
      {
        "date": "26 Agu",
        "balance": 4755625,
        "note": "-Rp1.13M"
      },
      {
        "date": "29 Agu",
        "balance": 3945918,
        "note": "Red Defense Zone (< Rp4M)"
      },
      {
        "date": "31 Agu",
        "balance": 5333508,
        "note": "Kewajiban Sep Lunas "
      },
      {
        "date": "1 Sep",
        "balance": 4130865,
        "note": "Mandiri Rp4,05M (Investasi Claude Pro 2 Akun • Sisa Di Atas Floor Rp4M)"
      },
      {
        "date": "2 Sep (Live)",
        "balance": 9892741,
        "note": "Mandiri Rp9,78M • Total Kas Rp9,89M (Surplus +Rp5,89M di atas Floor!)"
      },
      {
        "date": "6 Sep (Live)",
        "balance": 8306524,
        "note": "Mandiri Rp6,85M • LINE Rp1,35M • Total Kas Rp8,30M (Surplus +Rp4,30M di atas Floor!)"
      }
    ],
    "recoveryRoadmap": {
      "stage1": "Rp4.000.000 (Hard Floor Defense Zone - PASSED )",
      "stage2": "Rp4.130.865 (Buffer + 2 Akun Claude Pro - PASSED )",
      "stage3": "Rp7.130.865 (Pelunasan Barber Underrated Rp3M - PASSED )",
      "stage4": "Rp8.306.524 (Live Saldo Kas Aman • Surplus +Rp4,30M di atas Floor!)"
    },
    "defenseProtocolRule": "Saldo likuid Rp8,30M (Surplus masif +Rp4,30M di atas Floor Rp4M). Pemasukan September sudah tembus Rp6.500.000 (65.0% tercapai). Fokus sekarang: Eksekusi sprint modul LMS Umi Elly & scale KAEL SaaS!",
    "fixedMonthlyBurn": 3025000,
    "estimatedRealBurn": 4500000,
    "monthlyIncomeTarget": 10000000,
    "runwayDays": 55,
    "runwayMonths": 1.8,
    "monthlyExpenses": [
      {
        "id": "exp-1",
        "category": "Uang istri",
        "estimatedAmount": 1200000,
        "amountText": "Rp1.200.000 (Lunas Sep )",
        "status": "Wajib",
        "isFixed": true,
        "notes": "Nafkah rutin bulanan September 2026 LUNAS terkirim",
        "isPaid": true,
        "paidDate": "31 Agu 2026"
      },
      {
        "id": "exp-2",
        "category": "Kewajiban rumah Mesir",
        "estimatedAmount": 500000,
        "amountText": "Rp500.000 (Lunas Sep )",
        "status": "Wajib",
        "isFixed": true,
        "notes": "Kewajiban bulanan Mesir September 2026 LUNAS ",
        "isPaid": true,
        "paidDate": "31 Agu 2026"
      },
      {
        "id": "exp-3",
        "category": "Internet / kuota",
        "estimatedAmount": 200000,
        "amountText": "Rp200.000",
        "status": "Wajib",
        "isFixed": true,
        "notes": "Koneksi kerja & dev",
        "isPaid": true,
        "paidDate": "7 Sep 2026"
      },
      {
        "id": "exp-4",
        "category": "ChatGPT Plus",
        "estimatedAmount": 360000,
        "amountText": "Rp360.000",
        "status": "Produktif / langganan aktif",
        "isFixed": true,
        "notes": "AI Dev workflow",
        "isPaid": false
      },
      {
        "id": "exp-5",
        "category": "Claude Pro (2 Akun)",
        "estimatedAmount": 720000,
        "amountText": "±Rp720.000 (2 Akun Aktif )",
        "status": "Produktif / langganan aktif",
        "isFixed": true,
        "notes": "Claude Pro (2 Akun Aktif) untuk AI Coding & High-Volume Reasoning",
        "isPaid": true,
        "paidDate": "1 Sep 2026"
      },
      {
        "id": "exp-6",
        "category": "Wavebox",
        "estimatedAmount": 245000,
        "amountText": "±Rp245.000",
        "status": "Produktif / langganan aktif",
        "isFixed": true,
        "notes": "Multi-account workspace browser",
        "isPaid": false
      },
      {
        "id": "exp-7",
        "category": "Kebutuhan makan / jajan rumah tangga",
        "estimatedAmount": "fleksibel",
        "amountText": "fleksibel (~Rp1.000.000 est.)",
        "status": "Wajib, fleksibel",
        "isFixed": false,
        "notes": "Kebutuhan pokok pangan",
        "isPaid": false
      },
      {
        "id": "exp-8",
        "category": "Kebutuhan anak",
        "estimatedAmount": "fleksibel",
        "amountText": "fleksibel",
        "status": "Wajib, fleksibel",
        "isFixed": false,
        "notes": "Popok, susu & kebutuhan bayi",
        "isPaid": false
      },
      {
        "id": "exp-9",
        "category": "Token / listrik",
        "estimatedAmount": "fleksibel",
        "amountText": "fleksibel",
        "status": "Wajib, fleksibel",
        "isFixed": false,
        "notes": "Listrik kerja & rumah",
        "isPaid": true,
        "paidDate": "7 Sep 2026"
      },
      {
        "id": "exp-10",
        "category": "Transport / kebutuhan harian",
        "estimatedAmount": "fleksibel",
        "amountText": "fleksibel",
        "status": "Wajib, fleksibel",
        "isFixed": false,
        "notes": "Bensin & mobilitas offline",
        "isPaid": false
      },
      {
        "id": "exp-11",
        "category": "Imunisasi / kesehatan",
        "estimatedAmount": "tidak selalu bulanan",
        "amountText": "tidak selalu bulanan",
        "status": "Wajib, fleksibel",
        "isFixed": false,
        "notes": "Medis darurat / jadwal vaksin",
        "isPaid": false
      }
    ],
    "transactions": [
      {
        "id": "tx-ifdony-azharuna-sep",
        "date": "4 Sep 2026",
        "type": "income",
        "amount": 500000,
        "accountName": "Mandiri",
        "category": "Client Payment (Lunas)",
        "description": "Desain Branding & Logo Azharuna (Ustadz Ifdony) (+Rp500.000 Lunas )",
        "createdAt": "2026-09-04T10:00:00.000Z"
      },
      {
        "id": "tx-barber-lunas-sep2",
        "date": "2 Sep 2026",
        "type": "income",
        "amount": 3000000,
        "accountName": "Mandiri",
        "category": "Client Payment (Pelunasan 100%)",
        "description": "Pelunasan 100% Barber POS & Membership System (+Rp3.000.000 Lunas Penuh )",
        "createdAt": "2026-09-02T15:45:00.000Z"
      },
      {
        "id": "tx-umi-elly-dp-sep2",
        "date": "2 Sep 2026",
        "type": "income",
        "amount": 3000000,
        "accountName": "Mandiri",
        "category": "Client Payment (Termin 1 DP)",
        "description": "Termin 1 DP 50% Kickoff LMS Peradaban Islam Azhariyah Umi Elly (+Rp3.000.000 Masuk )",
        "createdAt": "2026-09-02T15:50:00.000Z"
      },
      {
        "id": "tx-claude-2acc",
        "date": "1 Sep 2026",
        "type": "expense",
        "amount": 1202643,
        "accountName": "Mandiri",
        "category": "AI & Operational Tools",
        "description": "Upgrade & Langganan Claude Pro 2 Akun + Pengeluaran Produktif (-Rp1.202.643)",
        "createdAt": "2026-09-01T14:41:00.000Z"
      },
      {
        "id": "tx-mandiri-out-35k",
        "date": "31 Agu 2026",
        "type": "expense",
        "amount": 35000,
        "accountName": "Mandiri",
        "category": "Pengeluaran Harian",
        "description": "Pengeluaran harian rekening Mandiri (-Rp35.000)",
        "createdAt": "2026-08-31T13:37:00.000Z"
      },
      {
        "id": "tx-mesir-sep-2026",
        "date": "31 Agu 2026",
        "type": "expense",
        "amount": 500000,
        "accountName": "Mandiri",
        "category": "Kewajiban Rutin",
        "description": "Kewajiban rumah Mesir bulan September 2026 (Rp500.000 Lunas )",
        "createdAt": "2026-08-31T10:55:00.000Z"
      },
      {
        "id": "tx-in-31aug-906k",
        "date": "31 Agu 2026",
        "type": "income",
        "amount": 906000,
        "accountName": "Mandiri",
        "category": "Client Payment / Revenue",
        "description": "Pemasukan kas masuk rekening Mandiri (+Rp906.000)",
        "createdAt": "2026-08-31T09:15:00.000Z"
      },
      {
        "id": "tx-istri-sep-2026",
        "date": "31 Agu 2026",
        "type": "expense",
        "amount": 1200000,
        "accountName": "Mandiri",
        "category": "Nafkah Keluarga",
        "description": "Kirim uang nafkah istri bulan September 2026 (Rp1.200.000 Lunas )",
        "createdAt": "2026-08-31T10:25:00.000Z"
      },
      {
        "id": "tx-barber-dp-1",
        "date": "29 Agu 2026",
        "type": "income",
        "amount": 3000000,
        "accountName": "Mandiri",
        "category": "Client Payment (DP 50%)",
        "description": "DP 50% Kickoff Barber Membership & Loyalty System (Barber Underrated)",
        "createdAt": "2026-08-29T03:52:00.000Z"
      },
      {
        "id": "tx-init-1",
        "date": "29 Agu 2026",
        "type": "balance_update",
        "amount": 3867000,
        "accountName": "Mandiri",
        "category": "Saldo Live",
        "description": "Update saldo harian rekening Mandiri awal",
        "createdAt": "2026-08-29T03:50:00.000Z"
      }
    ]
  },
  "todayBlocks": [
    {
      "id": "tb-1",
      "projectId": "p-hamasah-ai",
      "blockType": "Growth Block",
      "projectName": "Hamasah Internasional - Integrasi AI Website",
      "action": "Meeting dengan owner Hamasah Internasional: discovery integrasi AI ke website & petakan kebutuhan",
      "timeboxMinutes": 60,
      "isDone": false,
      "rule": "Gali kebutuhan use-case AI secara spesifik, pastikan value jelas sebelum kasih estimasi harga."
    },
    {
      "id": "tb-2",
      "projectId": "p-umi-elly",
      "blockType": "Deep Work 1",
      "projectName": "Umi Elly - LMS Azhariyah",
      "action": "Review platform yang sudah live bareng Umi Elly & input kurikulum serta konten materi",
      "timeboxMinutes": 60,
      "isDone": false,
      "rule": "Pastikan platform nyaman digunakan Umi Elly dan alur pengisian kurikulum tersusun rapi."
    },
    {
      "id": "tb-3",
      "projectId": "p-pgs-tour",
      "blockType": "Deep Work 2",
      "projectName": "Website PGS Tour",
      "action": "Review live demo pgstour.vercel.app & siapkan materi presentasi ke owner",
      "timeboxMinutes": 50,
      "isDone": false,
      "rule": "Website sudah live 15/15 static pages, fokus closing & kesepakatan harga."
    },
    {
      "id": "tb-4",
      "projectId": "p-ifdony-azharuna",
      "blockType": "Deep Work 3",
      "projectName": "Logo Azharuna (Ustadz Ifdony)",
      "action": "Eksplorasi konsep simbol logo, tipografi arab/modern & visual mockup",
      "timeboxMinutes": 60,
      "isDone": false,
      "rule": "Fokus desain logo clean & elegan sampai siap presentasi."
    },
    {
      "id": "tb-5",
      "projectId": "p-umi-atiyah",
      "blockType": "Admin/Maintenance",
      "projectName": "Umi Atiyah & KPI",
      "action": "Follow up pelunasan Rp200rb Umi Atiyah & pantau respon penawaran Rp14jt KPI",
      "timeboxMinutes": 20,
      "isDone": false,
      "rule": "Jaga cashflow: pastikan reminder santai terkirim ke Umi Atiyah."
    }
  ],
  "projects": [
    {
      "id": "p-dreammecca",
      "name": "DreamMecca Platform",
      "lane": "client_delivery",
      "boardColumn": "DONE",
      "status": "Done",
      "paymentStatus": "Paid",
      "valueText": "Lunas & Selesai Tuntas ",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P1",
      "currentGoal": "100% SELESAI & TUNTAS! (Platform live & serah terima beres)",
      "nextAction": "Project tuntas 100% - Bebas utang deliverable & pikiran plong ",
      "definitionOfDone": "Platform DreamMecca live & tuntas diserahkan ke klien ",
      "rule": "Finishing deliverable yang sudah lunas dari lama agar bebas tanggungan.",
      "billingMilestone": "Paid in Full (Historical)",
      "followUpDeadline": "Finishing malam ini"
    },
    {
      "id": "p-zalvice",
      "name": "Zalvice Logo",
      "lane": "client_delivery",
      "boardColumn": "DONE",
      "status": "Done",
      "paymentStatus": "Paid",
      "valueText": "Bagian dari Rp1,2 jt, sudah dibayar",
      "nominalNumeric": 600000,
      "paidNumeric": 600000,
      "unpaidNumeric": 0,
      "priority": "P1",
      "currentGoal": "Logo Zalvice SELESAI & TUNTAS! (Paket Rp1,2M Lunas)",
      "nextAction": "Handover master assets & mockup ke Bang Edo",
      "definitionOfDone": "Logo Zalvice selesai & diterima klien ",
      "billingMilestone": "Paid in Full (Paket Rp1,2M)",
      "followUpDeadline": "Done "
    },
    {
      "id": "p-barber",
      "name": "Barber Membership & Loyalty System (Barber Underrated)",
      "lane": "client_delivery",
      "boardColumn": "DONE",
      "status": "Done",
      "paymentStatus": "Paid",
      "valueText": "Rp6.000.000 (100% LUNAS FULL PAYMENT )",
      "nominalNumeric": 6000000,
      "paidNumeric": 6000000,
      "unpaidNumeric": 0,
      "priority": "P1",
      "currentGoal": "100% TUNTAS & LUNAS FULL PAYMENT! (DP Rp3M + Pelunasan Rp3M Masuk Kas Mandiri)",
      "nextAction": "Dampingi operasional opening & maintenance bila ada request minor, lalu bungkus jadi portofolio studi kasus!",
      "definitionOfDone": "Website & POS Kasir Barber live, serah terima tuntas, uang lunas Rp6.000.000 ",
      "rule": "Barbershop 100% LUNAS & tuntas.",
      "billingMilestone": "100% Paid in Full (Rp6.000.000 Lunas )",
      "followUpDeadline": "Done ",
      "newsArticle": "Ini dia definisi proyek impian setiap developer: pengerjaan tuntas, klien puas, dan bayaran 100% LUNAS tanpa drama cicilan! Sistem Membership & POS Kasir Barber Underrated kini resmi berlayar penuh di lapangan operasional.\n\n### 1. Ekosistem Kasir & Loyalty yang Bikin Pelanggan Balik Lagi\nBukan cuma aplikasi kasir biasa buat catat potong rambut, sistem ini dirancang buat ngunci loyalitas pelanggan:\n- Membership tiering & poin loyalty otomatis tiap kali pelanggan selesai potong rambut.\n- Dashboard kasir sat-set yang gampang dipake kapster tanpa ribet pencet banyak menu.\n- Rekapitulasi omzet harian & komisi kapster yang transparan dan anti-selisih.\n\n### 2. Skor Finansial Sempurna: Rp6.000.000 Masuk Kas Penuh!\nDari deal awal Rp6.000.000, DP Rp3.000.000 dan Pelunasan Rp3.000.000 semuanya sudah landing di kas Mandiri. Sisa tagihan: Rp0! Bebas tanggungan utang kerjaan dan pikiran plong 100%!",
      "newsCritique": "Status proyek ini adalah bintang emas (gold standard) di workspace lu: tuntas teknis dan tuntas cuan. Catatan redaksi: segera jadikan alur studi kasus dan tangkapan layar sistem ini sebagai portofolio premium buat closing barbershop dan salon lain dengan nilai kontrak yang lebih tinggi!"
    },
    {
      "id": "p-kael-product",
      "name": "Setting KAEL (Core Product)",
      "lane": "own_product",
      "boardColumn": "DOING",
      "status": "Doing",
      "paymentStatus": "Recurring/Pipeline",
      "valueText": "Core SaaS Asset (Active Setup)",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P2",
      "currentGoal": "Setting konfigurasi core product & fix blocker demo/closing",
      "nextAction": "Kunci konfigurasi role kasir vs owner, QRIS static flow, dan gaspol demo ke 3-5 calon tenant UMKM!",
      "definitionOfDone": "Semua setting dan flow kasir/owner berjalan stabil",
      "rule": "Jangan nambah fitur random! Fokus setting hal yang langsung mendukung penjualan.",
      "billingMilestone": "Product Stability & Pilot Ready",
      "followUpDeadline": "Selesai setting hari ini",
      "newsArticle": "Sebagai aset SaaS inti (Core Product) milik sendiri, KAEL gak boleh cuma jadi proyek kodingan yang gak kunjung ketemu market! Hari ini tim redaksi memotret fokus tajam di dapur pengembangan: kita setop nambahin fitur-fitur random yang bikin pusing, dan banting setir ke stabilitas flow kasir dan demo closing tenant.\n\n### 1. Beresin Bottleneck Sebelum Terjun ke Lapangan\nFokus sprint saat ini adalah menuntaskan konfigurasi penting yang langsung nentuin closing di depan calon klien:\n- Pemisahan hak akses kasir vs owner biar data keuangan owner aman dan kasir gak bisa ngutak-atik laporan.\n- Sinkronisasi staff shift kasir dan mitigasi bug double pay pada modul self-order.\n- Integrasi QRIS Static flow yang simpel biar tenant UMKM gak ribet verifikasi transaksi.\n\n### 2. Target Nyata: 3-5 Pilot Customer Pertama\nIni bukan saatnya mempercantik kodingan di ruang hampa. Begitu settingan stabil, aksi berikutnya adalah bawa demo langsung ke UMKM lokal untuk mengamankan 3-5 tenant berbayar pertama!",
      "newsCritique": "Godaan terbesar saat bikin produk SaaS sendiri adalah 'Product Perfectionism'—terus-terusan koding fitur baru karena takut ditolak pasar. Evaluasi tegas redaksi: batasi waktu setting maksimal 1 hari lagi! Kejar pilot customer nyata, validasi apakah UMKM mau bayar, dan dengarkan kritik langsung dari kasir di lapangan."
    },
    {
      "id": "p-laptopbisnis",
      "name": "Laptopbisnis Logo",
      "lane": "client_delivery",
      "boardColumn": "DONE",
      "status": "Done",
      "paymentStatus": "Paid",
      "valueText": "Bagian dari Rp1,2 jt, sudah dibayar",
      "nominalNumeric": 600000,
      "paidNumeric": 600000,
      "unpaidNumeric": 0,
      "priority": "P1",
      "currentGoal": "Logo Laptopbisnis SELESAI & TUNTAS! (Paket Rp1,2M Lunas)",
      "nextAction": "Handover master assets & mockup ke klien",
      "definitionOfDone": "Logo Laptopbisnis selesai & diterima klien ",
      "rule": "Queue: Eksekusi segera setelah Zalvice tuntas",
      "billingMilestone": "Paid in Full",
      "followUpDeadline": "Done "
    },
    {
      "id": "p-ifdony-azharuna",
      "name": "Logo Azharuna (Ustadz Ifdony)",
      "lane": "client_delivery",
      "boardColumn": "DOING",
      "status": "Doing",
      "paymentStatus": "Paid",
      "valueText": "Rp500.000 (Lunas September 2026 )",
      "nominalNumeric": 500000,
      "paidNumeric": 500000,
      "unpaidNumeric": 0,
      "priority": "P1",
      "currentGoal": "Pengerjaan Desain Branding & Eksplorasi Logo Azharuna",
      "nextAction": "Eksplorasi konsep simbol, tipografi arab/modern & visual mockup",
      "definitionOfDone": "Master file logo diserahkan & pembayaran Rp500.000 lunas ",
      "billingMilestone": "100% Paid in Full (Rp500.000 Lunas)",
      "followUpDeadline": "Done "
    },
    {
      "id": "p-umi-elly",
      "name": "Umi Elly - LMS Peradaban Islam Azhariyah",
      "lane": "client_delivery",
      "boardColumn": "DOING",
      "status": "Doing",
      "paymentStatus": "Partial",
      "valueText": "Deal Rp7.000.000 (Platform Live • Review & Input Kurikulum)",
      "nominalNumeric": 7000000,
      "paidNumeric": 3000000,
      "unpaidNumeric": 4000000,
      "priority": "P1",
      "currentGoal": "Platform sudah dibangun! Tahap review bersama Umi Elly & input kurikulum + konten",
      "nextAction": "Review platform bareng Umi Elly dan dampingi input kurikulum serta modul materi",
      "definitionOfDone": "Modul LMS Peradaban Islam Azhariyah live & deploy",
      "rule": "DP Rp3M sudah masuk kas: Gaspol sprint pengerjaan modul lengkap dengan standar kualitas tinggi.",
      "billingMilestone": "Termin 1: DP Rp3.000.000 (LUNAS ) • Termin 2: Rp2.000.000 • Termin 3: Rp2.000.000",
      "followUpDeadline": "Sprint Kickoff Aktif",
      "newsArticle": "Gak ada yang lebih bikin bersemangat daripada ngebangun platform edukasi yang punya visi peradaban nyata! Proyek LMS Peradaban Islam Azhariyah bareng Umi Elly resmi masuki babak paling seru: platform intinya udah kelar dibangun, dan sekarang kita lagi sprint bareng Umi Elly buat review menyeluruh serta input kurikulum dan modul materi belajar.\n\n### 1. Dapur Pacu LMS: Dari Desain Sampai Ruang Belajar Digital\nPlatform ini dirancang khusus biar santri dan pembelajar gak bosen dan gampang nyerap ilmu peradaban Islam:\n- Arsitektur modul pembelajaran terstruktur (video kajian, silabus, dan materi bacaan interaktif).\n- UI/UX yang ramah santri maupun orang tua dengan tema visual khas Azhariyah yang sejuk dan berwibawa.\n- Sistem tracking progres belajar santri biar pengajar tahu bab mana yang udah tuntas dipelajari.\n\n### 2. Situasi Kas Nyata: DP Rp3 Juta Sudah Masuk Rekening\nIni yang bikin tim makin gaspol: komitmen Umi Elly sangat solid! Dari total deal Rp7.000.000, termin pertama DP sebesar Rp3.000.000 sudah resmi mendarat aman di kas Mandiri. Sisa tagihan Rp4.000.000 akan cair di Termin 2 (Rp2 Juta) dan Termin 3 (Rp2 Juta) begitu kurikulum live.\n\n### 3. Fokus Hari Ini: Input Kurikulum & Final Polish\nTahap paling krusial sekarang bukan lagi utak-atik kodingan backend, melainkan mendampingi Umi Elly mengonversi materi cetak dan kajian menjadi silabus digital yang siap rilis publik!",
      "newsCritique": "Progress proyek ini sehat banget karena didukung DP nyata Rp3 Jt di depan kas. Evaluasi penting: dampingi proses input materi dengan sabar tapi tetap punya batas waktu jelas (timebox). Jangan biarkan review kurikulum berlarut-larut tanpa deadline, karena termin pelunasan Rp4 Juta baru bisa ditagih begitu modul live!"
    },
    {
      "id": "p-el-massa",
      "name": "Katalog Web El Massa Tour & Travel",
      "lane": "client_delivery",
      "boardColumn": "DONE",
      "status": "Done",
      "paymentStatus": "Expected",
      "valueText": "12 Paket Ibadah Live (darcia2024/elmassa-katalog)",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P2",
      "currentGoal": "Proyek Galeri & Katalog Web El Massa 100% siap & aktif! 12 paket unlocked ber-flyer HD, itinerary harian, live seat tracker, simulator tabungan baitullah, dashboard admin, terhubung WA resmi +62 811-7171-5125, tersinkronisasi branch main (cache V36).",
      "nextAction": "1. Kirim pesan serah terima resmi dan link katalog live ke manajemen El Massa Tour & Travel via WhatsApp resmi (+62 811-7171-5125).\n2. Terbitkan Invoice Pelunasan Final hari ini juga sebelum menyerahkan master credentials dan akses server produksi.\n3. Buatkan panduan video tutorial singkat 2 menit tentang cara operasional Dashboard Admin untuk tim CS El Massa.",
      "definitionOfDone": "12 paket ibadah live, sistem operasional penuh, dan laporan tuntas diterima klien",
      "rule": "Semua fitur katalog & admin sudah beroperasi penuh. Fokus ke serah terima dan tindak lanjut pembayaran.",
      "billingMilestone": "Serah Terima Proyek Web & Invoice Final",
      "followUpDeadline": "Hari ini",
      "newsArticle": "Bayangin situasi ini: calon jemaah lagi semangat-semangatnya pengen daftar umrah atau nemenin orang tua ke Baitullah. Tapi pas ngehubungin admin travel, mereka malah dikirimin belasan file PDF berat ukuran puluhan MB yang bikin memori HP jebol. Belum lagi jemaah harus bolak-balik nanya: *\"Kak, ini hotelnya berapa meter dari pelataran?\", \"Landing Madinah apa Jeddah?\", \"Bisa cicil tabungan per bulan gak?\"*\n\nAdmin kewalahan balesin ratusan chat serupa setiap hari, sementara calon jemaah yang butuh kepastian cepat keburu hilang minat atau pindah ke travel sebelah. Problem klasik di industri travel inilah yang bikin tim kita gerah sampai akhirnya kita putusin: **Website El Massa Tour & Travel gak boleh cuma jadi etalase brosur pajangan zaman purba—ini harus jadi mesin konversi digital yang serba sat-set, interaktif, dan langsung ngunci niat jemaah!**\n\nDan hari ini, kabar gembira dari lini produksi: **Proyek Galeri & Katalog Web El Massa resmi 100% siap tempur, tuntas, dan berstatus LIVE penuh di jalur produksi!** Simak laporan lapangan eksklusifnya di bawah ini:\n\n## 1. 12 Paket Ibadah Lengkap Sudah Tersedia\n\nSeluruh paket ibadah kini sudah resmi ditampilkan di katalog, lengkap dengan brosur grafis resolusi tinggi, pilihan maskapai ternama, hotel strategis, dan itinerary harian yang detail.\n\n| Program | Tanggal | Durasi | Maskapai | Highlight | Harga Mulai |\n| --- | --- | ---: | --- | --- | ---: |\n| Umrah Special November Reguler | 03–13 Nov 2026 | 10 Hari | Saudia Airlines | Landing Madinah, Grand Al Massa & Daar El Naeem | **Rp34,7 Jt** |\n| Umrah Spesial Ust. Hanan Attaki | 16/17–26/27 Nov 2026 | ±11 Hari | Saudia Airlines | Direct SV821, pilihan Jakarta & Pangkalpinang | **Rp35 Jt** |\n| Umrah Akhir Tahun Landing Madinah | 12–23 Des 2026 | 12 Hari | Saudia Airlines | Penutup tahun 12 Hari landing Madinah | **Rp32,9 Jt** |\n| Umrah Nisfu Sya'ban di Mekkah | 20–30 Jan 2027 | 11 Hari | Garuda Indonesia | Direct Flight, malam Nisfu Sya'ban di Baitullah | **Rp34,7 Jt** |\n| Umrah Istimewa Awal Ramadan | 05–15 Feb 2027 | 11 Hari | Saudia Airlines | Pahala puasa awal Ramadan | **Rp35,7 Jt** |\n| Umrah Sayang Orang Tua Bersama IMB | 16–27 Mar 2027 (Syawal) | 12 Hari | Garuda Indonesia | Hotel Olayan Ajyad 0 KM, ramah lansia | **Rp35,7 Jt** |\n| Umrah Bersama Ust. Dr. H. Muhammad Kurnia | 16–27 Mar 2027 | 12 Hari | Saudia Airlines | Bimbingan intensif Syawal, Hotel 0 KM | **Rp35,7 Jt** |\n| Umrah Lebih Nyaman Syawal Program 9H | Maret 2027 | 9 Hari | Garuda Indonesia | Program 9 Hari Syawal | **Rp31,7 Jt** |\n| Umrah Lebih Nyaman Syawal Program 12H | Maret 2027 | 12 Hari | Saudia Airlines | Program 12 Hari Syawal | **Rp34,7 Jt** |\n| Umrah Muharram Awal Musim | Juni 2027 | 10 Hari | Saudia Airlines | Pembuka musim baru 1449 H Landing Madinah | **Rp31,7 Jt** |\n| Umrah Liburan Sekolah Program 9H | Akhir Juni 2027 | 9 Hari | Qatar / Etihad | Cocok untuk keluarga dan anak sekolah | **Rp30,9 Jt** |\n| Umrah Liburan Sekolah Program 12H | Akhir Juni 2027 | 12 Hari | Saudia Airlines | Liburan sekolah durasi panjang | **Rp33,7 Jt** |\n\n---\n\n## 2. Fitur Interaktif untuk Membantu Jemaah Mengambil Keputusan\n\nWebsite ini bukan sekadar brosur digital statis, melainkan platform interaktif yang memudahkan calon jemaah dalam membandingkan paket dan menghitung rencana keberangkatan mereka.\n\n| Fitur | Deskripsi | Manfaat untuk Jemaah |\n| --- | --- | --- |\n| **Dual Flyer Card** *(Ust. Hanan Attaki)* | Modal interaktif untuk membandingkan opsi keberangkatan Jakarta vs Pangkalpinang (PGK) | Memudahkan jemaah melihat perbedaan harga dan benefit secara langsung tanpa harus membuka dokumen terpisah |\n| **Live Seat Tracker** | Menampilkan status ketersediaan kursi secara real-time (*Tersedia*, *Terbatas*, *Hampir Penuh*, *Penuh*) | Memberikan transparansi kuota dan membantu jemaah segera mengamankan kursi sebelum kehabisan |\n| **Simulator Tabungan Baitullah** | Kalkulator estimasi setoran tabungan bulanan berdasarkan target waktu keberangkatan | Membantu jemaah merencanakan pembiayaan ibadah secara lebih realistis dan terstruktur |\n| **WhatsApp Auto Format** | Rincian paket dan hasil estimasi tabungan langsung terkonversi menjadi template pesan WhatsApp | Mempercepat proses konsultasi ke nomor resmi CS tanpa harus mengetik ulang data |\n| **Smart Multi-Filter** | Pencarian berdasarkan kategori, kota keberangkatan, maskapai, dan bulan | Mempercepat pencarian paket sesuai preferensi dan anggaran jemaah |\n\n---\n\n## 3. Dashboard Admin Mandiri\n\nUntuk mempermudah pengelolaan operasional tanpa harus bergantung pada tim teknis, website ini telah dilengkapi dashboard admin terintegrasi.\n\n| Area Pengelolaan | Kemampuan Fitur |\n| --- | --- |\n| **Katalog Paket** | Tambah, edit, dan hapus paket ibadah secara langsung |\n| **Status Ketersediaan Seat** | Pembaruan status kuota kursi secara berkala |\n| **Konfigurasi Operasional** | Pengaturan nomor kontak WhatsApp CS, kota keberangkatan, dan data maskapai |\n\n---\n\n## 4. Stabilitas & Infrastruktur Sistem\n\n| Komponen | Status / Spesifikasi |\n| --- | --- |\n| **Repositori Kode** | Tersinkronisasi penuh di branch `main` (`darcia2024/elmassa-katalog`) |\n| **Manajemen Cache** | Menggunakan `EL_MASSA_APP_DATA_V36` untuk memastikan browser pengunjung selalu memuat data terbaru |\n| **Integrasi Kontak Resmi** | Terhubung langsung ke WhatsApp CS: **+62 811-7171-5125** |\n\n---\n\n## Kesimpulan\n\nWebsite El Massa sekarang sudah berkembang dari sekadar katalog menjadi platform penjualan digital Umrah dengan alur interaksi:\n\n> **Cari Paket** → **Bandingkan Detail & Flyer** → **Pantau Sisa Seat** → **Hitung Simulasi Tabungan** → **Hubungi CS via WhatsApp Otomatis**",
      "newsCritique": "Kodingan beres, 12 paket live, fitur interaktif jalan mulus—secara teknis eksekusi lu emang gokil no debat bro! TAPI, sebagai sesama founder yang paham dinamika bisnis software & agensi, redaksi wajib kasih reality check yang pedas tapi menyelamatkan bisnis lu:\n\n1. **Jebakan 'Terlalu Baik Hati' (Scope Creep vs Cash Flow)**: Sistem ini sekarang sudah 100% beroperasi di lini produksi publik, tapi invoice pelunasan belum lu tagih secara tegas. Posisi tawar lu saat ini lagi rawan! Begitu klien merasa semua fitur impian mereka sudah live dan bisa dipakai jemaah, urgensi mereka untuk melunasi pembayaran bakal melambat drastis. Kunci komitmen pembayaran hari ini juga!\n2. **Kunci Akses Master & Jangan Lepas Server**: Jangan pernah serahkan master credentials admin, akses hosting/domain, atau akses repository GitHub sebelum uang termin pelunasan sah mendarat di mutasi rekening. Sekali akses penuh dilepas tanpa jaminan tertulis, urusan pelunasan bisa berubah jadi drama follow-up berbulan-bulan.\n3. **Validasi Funnel Konversi Nyata**: Jangan puas cuma karena websitenya kelihatan cakep. Pantau metrik konversi aslinya: berapa banyak jemaah yang masuk lewat fitur *Simulator Tabungan Baitullah* sampai beneran klik tombol WhatsApp CS? Kalau angka klik CS masih rendah, berarti teks CTA (Call-to-Action) di flyer card butuh sedikit dipoles lagi."
    },
    {
      "id": "p-pgs-tour",
      "name": "Website PGS Tour & Travel",
      "lane": "client_delivery",
      "boardColumn": "DONE",
      "status": "Done",
      "paymentStatus": "Expected",
      "valueText": "100% Live Production (pgstour.vercel.app)",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P2",
      "currentGoal": "Website resmi PGS Tour & Travel 100% siap tayang di production (pgstour.vercel.app)! Redesign clean & premium, legalitas PPIU Kemenag RI, foto asli jamaah di Quba, perbaikan bug galeri mobile (WebP+JPEG HD), dan 15/15 static pages live.",
      "nextAction": "1. Lakukan final handover dan serah terima link live pgstour.vercel.app ke manajemen PT Permana Group Sejahtera via WhatsApp admin.\n2. Terbitkan dan kirimkan Invoice Pelunasan Final proyek website hari ini juga sebelum menyerahkan akses penuh domain dan hosting production.\n3. Siapkan panduan singkat operasional link WhatsApp booking dan formulir konsultasi untuk admin customer service PGS Tour.",
      "definitionOfDone": "Website PGS Tour 100% live di Vercel, seluruh 15 halaman aktif, bug galeri HP terselesaikan, dan serah terima diterima klien",
      "rule": "Website sudah live di production. Prioritaskan serah terima resmi ke manajemen PGS dan kawal invoice pelunasan.",
      "billingMilestone": "Serah Terima Website Production & Invoice Final",
      "followUpDeadline": "Hari ini",
      "newsArticle": "Bikin website travel Umroh itu tantangannya bukan cuma soal pasang foto Ka'bah terus selesai. Kalau tampilan websitenya berantakan, navigasi di HP lemot, galeri fotonya error gak kebuka, dan legalitasnya samar-samar, calon jamaah bakal langsung ragu dan batal daftar. Apalagi ibadah Umroh itu urusan amanah besar dengan nilai puluhan juta rupiah—calon jamaah butuh rasa percaya 100% sebelum klik tombol booking!\n\nProblem itulah yang kita beresin tuntas di proyek **PGS Tour & Travel (PT Permana Group Sejahtera)**. Kita gak cuma sekadar moles kosmetik tampilan biar kelihatan keren, tapi merombak total arsitektur digitalnya jadi **mesin konversi travel modern yang super meyakinkan, elegan, dan sat-set diakses jamaah dari HP apapun!**\n\nDan hari ini, kabar gembira dari lini produksi: **Website resmi PGS Tour & Travel kini sudah resmi rampung, lolos uji render 15 halaman statis, dan 100% LIVE mengudara di production!** Simak laporan lengkap pencapaian di lapangan berikut ini:\n\n## 1. Redesign Website: Lebih Simpel, Elegan & Terpercaya\n\nTampilan website diperbarui secara menyeluruh dengan pendekatan visual yang lebih **clean, premium, dan modern**, namun tetap menjaga karakter travel Umroh yang hangat dan terpercaya.\n\nPerubahan utama meliputi:\n- Navigasi mobile dibuat lebih sederhana dan nyaman digunakan.\n- Tombol WhatsApp Booking dijadikan CTA utama agar calon jamaah tidak bingung.\n- Trust Strip legalitas dan jaminan layanan dibuat lebih rapi serta mudah dibaca.\n- Informasi hotel diperjelas menjadi **“Jarak Hotel dekat ke Masjid”**.\n- Halaman Visa Umroh didesain ulang dari tabel kaku menjadi **kartu paket modern**.\n- Elemen visual yang terlalu ramai dikurangi agar website terasa lebih premium.\n\nHasil akhirnya adalah tampilan yang tidak lagi terasa seperti website company profile biasa, tetapi lebih mendekati **high-converting travel website** yang memiliki daya jual.\n\n---\n\n## 2. Konten Asli, Legalitas & Kredibilitas Brand Diperkuat\n\nWebsite kini tidak lagi bergantung pada visual placeholder.\n\nPada halaman **Tentang Kami**, gambar lama diganti dengan **foto asli dokumentasi jamaah PGS Tour**, termasuk dokumentasi rombongan di Masjid Quba.\n\nInformasi perusahaan juga ditata lebih jelas, mencakup:\n- Profil **PT Permana Group Sejahtera**\n- Legalitas dan izin **PPIU Kemenag RI**\n- Nilai amanah dan pelayanan travel\n- Dokumentasi perjalanan jamaah\n- Informasi layanan Umroh secara transparan\n\nHal ini membuat website memiliki unsur **social proof dan trust** yang jauh lebih kuat dibanding sebelumnya.\n\n---\n\n## 3. Bug Mobile & Galeri Jamaah Berhasil Distabilkan\n\nSalah satu masalah penting sebelumnya adalah adanya foto galeri yang tidak muncul pada beberapa perangkat HP.\n\nMasalah tersebut berhasil ditelusuri hingga ke konflik CSS pada sistem animasi galeri.\n\nPerbaikannya meliputi:\n- Perbaikan sistem opacity dan scroll animation.\n- Penambahan fallback format gambar **WebP + JPEG HD**.\n- Optimalisasi agar galeri tampil stabil di Android maupun iOS.\n- Lightbox galeri tetap dapat dibuka secara fullscreen.\n\nSekarang seluruh dokumentasi jamaah dapat tampil dengan lebih stabil tanpa ada foto yang hilang.\n\n---\n\n## 4. Seluruh Halaman Utama Sudah Aktif\n\n| Halaman | Fungsi |\n| --- | --- |\n| **Beranda** | Hero Ka'bah, legalitas, paket pilihan, galeri, keunggulan dan testimoni |\n| **Tentang Kami** | Profil perusahaan, legalitas PPIU dan dokumentasi asli |\n| **Perjalanan** | Katalog paket Umroh dan detail perjalanan |\n| **Visa Umroh** | Pilihan layanan Visa Saudi dan Visa Umroh |\n| **Galeri** | Dokumentasi asli jamaah dengan lightbox fullscreen |\n| **Kemitraan** | Informasi peluang kerja sama dan agen |\n| **Konsultasi** | Jalur konsultasi langsung ke WhatsApp admin |\n\nSeluruh halaman sudah dapat diakses secara normal melalui website production.\n\n---\n\n## 5. Production & Repository Sudah Aman\n\n| Komponen | Status / Spesifikasi |\n| --- | --- |\n| **Production Website** | `pgstour.vercel.app` |\n| **GitHub Repository** | `darcia2024/pgstour` |\n| **Status Build** | ✅ Clean / sukses |\n| **Static Pages** | ✅ 15/15 halaman berhasil prerender |\n| **Sinkronisasi Git** | Branch `master` dan `main` sudah tersinkronisasi 100% |\n\nBranch **master** dan **main** juga sudah tersinkronisasi sehingga source code project tersimpan rapi dan siap dikembangkan kembali jika dibutuhkan.\n\n---\n\n## Kesimpulan\n\nWebsite PGS Tour sekarang sudah berada pada tahap **production-ready** dan dapat digunakan sebagai website resmi perusahaan.\n\nFungsinya bukan lagi hanya sebagai tempat melihat profil perusahaan, tetapi sudah menjadi jalur digital lengkap:\n\n> **Kenal PGS** → **Bangun Kepercayaan** → **Lihat Paket** → **Cek Layanan** → **Konsultasi** → **Booking**\n\nWebsite ini sudah siap digunakan untuk mendukung marketing, branding, dan proses konversi calon jamaah PGS Tour & Travel.",
      "newsCritique": "Secara eksekusi teknis dan visual, hasil pengerjaan website PGS Tour ini jempolan banget bro—desainnya clean, visual kartu modern menggantikan tabel kaku, dan bug galeri di HP Android/iOS terselesaikan tuntas. TAPI, sebagai sesama founder, redaksi punya beberapa catatan kritis yang wajib lu kawal:\n\n1. **Jaga Momentum Pelunasan Sebelum Lepas Domain/Akses**: Website `pgstour.vercel.app` sekarang sudah live di production dan siap tayang publik. Posisi tawar lu sekarang ada di puncaknya! Segera kirim invoice pelunasan final hari ini juga. Jangan sampai akses domain custom atau master credential diserahkan sebelum pembayaran 100% mendarat di rekening.\n2. **Uji Jalur WhatsApp Booking di Berbagai Jam**: Tombol WhatsApp Booking sudah jadi CTA utama. Pastikan admin CS PGS Tour fast response saat menerima pesan dari jemaah. Kalau respon CS lebih dari 15-30 menit, bounce rate calon jemaah bakal tinggi meski websitenya sudah sekeren ini. Rekomendasikan CS pasang template auto-reply di luar jam kerja.\n3. **Optimasi SEO Lokal & Domain Custom**: Web saat ini masih di subdomain `pgstour.vercel.app`. Tahap berikutnya dorong klien untuk pairing domain utama resmi (`pgstour.com` / `pgstour.co.id`) agar branding PT Permana Group Sejahtera terlihat makin bonafide di mata calon jamaah dan mesin pencari Google."
    },
    {
      "id": "p-ar-ruwad",
      "name": "Ar-Ruwad Logo",
      "lane": "client_delivery",
      "boardColumn": "WAITING",
      "status": "Waiting Approval",
      "paymentStatus": "Paid",
      "valueText": "Sudah dibayar lama Rp600k",
      "nominalNumeric": 600000,
      "paidNumeric": 600000,
      "unpaidNumeric": 0,
      "priority": "P2",
      "currentGoal": "Menunggu respon pilihan logo",
      "nextAction": "Tunggu pilihan / feedback logo dari client",
      "definitionOfDone": "Client memilih salah satu konsep logo final",
      "billingMilestone": "Paid in Advance (Rp600k)",
      "followUpDeadline": "Touchpoint santai via WA"
    },
    {
      "id": "p-ibrahim-visa",
      "name": "Ibrahim Nawawi (Visa Student Kairo)",
      "lane": "client_delivery",
      "boardColumn": "WAITING",
      "status": "Waiting Payment",
      "paymentStatus": "Waiting Payment",
      "valueText": "Rp1.100.000 (Invoice Terbit)",
      "nominalNumeric": 1100000,
      "paidNumeric": 0,
      "unpaidNumeric": 1100000,
      "priority": "P2",
      "currentGoal": "Pengurusan Visa Entry Student Kairo",
      "nextAction": "Follow-up pembayaran & verifikasi kelengkapan dokumen (Paspor, Pasfoto, Tadaruj Dirasi)",
      "definitionOfDone": "Pembayaran Rp1.100.000 masuk & proses kedutaan berjalan",
      "billingMilestone": "Invoice INV/VES/2026/016 (Rp1.100.000)",
      "followUpDeadline": "Follow-up invoice via WA"
    },
    {
      "id": "p-markaz",
      "name": "Markaz Fiqih",
      "lane": "maintenance",
      "boardColumn": "QUEUE",
      "status": "Queue",
      "paymentStatus": "Free",
      "valueText": "Free Maintenance",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P3",
      "currentGoal": "Cuma beresin issue yang bener-bener urgent",
      "nextAction": "List bug → pilih maksimal 1-2 issue urgent → timebox 1-2 jam",
      "definitionOfDone": "Max 2 bug urgent tuntas tanpa merembet ke modul lain",
      "rule": "Markaz nggak boleh makan deep-work slot kerjaan berbayar.",
      "timebox": "1-2 jam per sesi",
      "billingMilestone": "Non-billable (Free)",
      "followUpDeadline": "Bila ada waktu luang setelah paid tasks"
    },
    {
      "id": "p-kael-marketing",
      "name": "KAEL - Offline Marketing",
      "lane": "bizdev",
      "boardColumn": "DOING",
      "status": "Doing",
      "paymentStatus": "Recurring/Pipeline",
      "valueText": "3-5 Pilot Customer Goal",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P2",
      "currentGoal": "Cari customer nyata & kumpulkan feedback lapangan",
      "nextAction": "Bawa brosur, demo langsung ke UMKM (Review/POS), follow-up yang sudah pernah lihat demo, cari 3-5 pilot customer pertama",
      "definitionOfDone": "3-5 pilot customer onboard & feedback tercatat",
      "rule": "Fokus tawarkan solusi nyata (Review/POS) sesuai kebutuhan bisnis mereka.",
      "billingMilestone": "SaaS Setup Fee / Monthly Subscription",
      "followUpDeadline": "1 outlet hari ini"
    },
    {
      "id": "p-upwork",
      "name": "Upwork Global Pipeline",
      "lane": "bizdev",
      "boardColumn": "QUEUE",
      "status": "Queue",
      "paymentStatus": "Recurring/Pipeline",
      "valueText": "USD High-Ticket Pipeline",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P2",
      "currentGoal": "Jaga peluang cashflow baru tanpa mengganggu delivery",
      "nextAction": "Apply 3-5 job berkualitas (Next.js, React, Supabase, dashboard, internal tools, POS, landing, bug fixing)",
      "definitionOfDone": "3 proposal spesifik terkirim",
      "rule": "Bukan spam proposal. Jangan buang Connects asal-asalan.",
      "billingMilestone": "Hourly / Fixed Price USD",
      "followUpDeadline": "Malam ini saat rilis job baru"
    },
    {
      "id": "p-watra",
      "name": "Rancangan LMS Al Madroj",
      "lane": "bizdev",
      "boardColumn": "DOING",
      "status": "Doing",
      "paymentStatus": "Expected",
      "valueText": "Platform Kelas LMS (Fase Rancangan Arsitektur)",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P1",
      "currentGoal": "Perancangan komprehensif arsitektur platform & modul kelas Al Madroj",
      "nextAction": "Penyusunan modul kurikulum, alur santri, role pengajar & scope teknis",
      "definitionOfDone": "Scope proposal terkirim",
      "billingMilestone": "Proposal Acceptance",
      "followUpDeadline": "Follow-up chat"
    },
    {
      "id": "p-kael-demo-percetakan",
      "name": "KAEL Demo by Industry (Percetakan)",
      "lane": "own_product",
      "boardColumn": "QUEUE",
      "status": "Queue",
      "paymentStatus": "Recurring/Pipeline",
      "valueText": "Industry-Specific Demo Flow",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P3",
      "currentGoal": "Bikin demo relate langsung ke bisnis percetakan (feedback nyata pemilik percetakan)",
      "nextAction": "Setup dummy data + flow yang relevan untuk Demo Percetakan",
      "definitionOfDone": "Tenant demo percetakan siap dipresentasikan",
      "rule": "Engine tetap sama, yang berubah mainly dummy data + flow yang relevan.",
      "billingMilestone": "Conversion Rate Multiplier",
      "followUpDeadline": "Siap untuk demo minggu ini"
    },
    {
      "id": "p-temantiket",
      "name": "Temantiket",
      "lane": "operations",
      "boardColumn": "WAITING",
      "status": "Ongoing",
      "paymentStatus": "Recurring/Pipeline",
      "valueText": "Business Operations Asset",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P3",
      "currentGoal": "Jaga operasional tanpa memakan daily deep work slot",
      "nextAction": "Eksekusi cuma jika ada order konkret / customer follow-up / operational issue",
      "definitionOfDone": "Operasional harian lancar",
      "rule": "Jangan masuk daily deep-work kecuali ada order, customer follow-up, issue, atau peluang revenue konkret.",
      "billingMilestone": "Operations Cashflow",
      "followUpDeadline": "As orders arrive"
    },
    {
      "id": "p-bedug",
      "name": "Bedug.net",
      "lane": "parking_lot",
      "boardColumn": "PARKED",
      "status": "Parked",
      "paymentStatus": "Parked",
      "valueText": "Lost / Cancelled (Rp2,2 jt)",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "PARKED",
      "currentGoal": "Lost Deal",
      "nextAction": "Archived (Deal dibatalkan / tidak lanjut)",
      "rule": "Tidak ada alokasi waktu."
    },
    {
      "id": "p-teh-umi",
      "name": "Teh Umi - E-reader Basic",
      "lane": "parking_lot",
      "boardColumn": "PARKED",
      "status": "Parked",
      "paymentStatus": "Parked",
      "valueText": "Lost / Dropped (Rp300k)",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "PARKED",
      "currentGoal": "Lost Project",
      "nextAction": "Archived (Cicilan dropped / tidak lanjut build)",
      "rule": "Tidak ada alokasi waktu."
    },
    {
      "id": "p-nemsyi",
      "name": "Nemsyi",
      "lane": "parking_lot",
      "boardColumn": "PARKED",
      "status": "Parked",
      "paymentStatus": "Parked",
      "valueText": "Paused Project",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "PARKED",
      "currentGoal": "Paused",
      "nextAction": "Jangan sentuh sebelum fokus utama selesai",
      "rule": "Jangan rebutan perhatian dengan kerjaan aktif sekarang."
    },
    {
      "id": "p-qohiroh",
      "name": "Qohiroh",
      "lane": "parking_lot",
      "boardColumn": "PARKED",
      "status": "Parked",
      "paymentStatus": "Parked",
      "valueText": "Lost / Dormant",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "PARKED",
      "currentGoal": "Dormant",
      "nextAction": "Archived",
      "rule": "Tidak ada alokasi waktu."
    },
    {
      "id": "p-saudi-addon",
      "name": "Saudi Add-on",
      "lane": "parking_lot",
      "boardColumn": "PARKED",
      "status": "Parked",
      "paymentStatus": "Parked",
      "valueText": "Dormant / Lost",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "PARKED",
      "currentGoal": "Dormant",
      "nextAction": "Archived",
      "rule": "Tidak ada alokasi waktu."
    },
    {
      "id": "p-komisi-interaksi",
      "name": "Rancangan Komisi Peduli Interaksi",
      "lane": "bizdev",
      "boardColumn": "WAITING",
      "status": "Waiting Payment",
      "paymentStatus": "Expected",
      "valueText": "Penawaran Rp14.000.000 Terkirim (Menunggu DP)",
      "nominalNumeric": 14000000,
      "paidNumeric": 0,
      "unpaidNumeric": 14000000,
      "priority": "P1",
      "currentGoal": "Penawaran harga Rp14jt sudah terkirim, menunggu transfer DP untuk kickoff build",
      "nextAction": "Tunggu konfirmasi & transfer DP Rp14jt untuk langsung mulai development",
      "definitionOfDone": "Draft rancangan komisi disetujui & siap masuk implementasi teknis",
      "billingMilestone": "DP Kickoff Proyek (Total Rp14.000.000)",
      "followUpDeadline": "Hari ini / Follow up WA"
    },
    {
      "id": "p-umi-atiyah",
      "name": "Umi Atiyah",
      "lane": "client_delivery",
      "boardColumn": "WAITING",
      "status": "Waiting Payment",
      "paymentStatus": "Partial",
      "valueText": "Selesai (Sisa Pelunasan Rp200.000)",
      "nominalNumeric": 200000,
      "paidNumeric": 0,
      "unpaidNumeric": 200000,
      "priority": "P1",
      "currentGoal": "Project Selesai 100%! Tinggal menunggu sisa pelunasan Rp200.000",
      "nextAction": "Follow up pelunasan Rp200.000 ke Umi Atiyah",
      "definitionOfDone": "Pelunasan Rp200.000 masuk & serah terima tuntas",
      "billingMilestone": "Pelunasan Akhir Rp200.000",
      "followUpDeadline": "Hari ini"
    },
    {
      "id": "p-hamasah-ai",
      "name": "Hamasah Internasional - Integrasi AI Website",
      "lane": "bizdev",
      "boardColumn": "DOING",
      "status": "Discovery / Lead",
      "paymentStatus": "Expected",
      "valueText": "Meeting Discovery AI (Pricing TBD)",
      "nominalNumeric": 0,
      "paidNumeric": 0,
      "unpaidNumeric": 0,
      "priority": "P1",
      "currentGoal": "Meeting hari ini dengan owner Hamasah Internasional untuk discovery integrasi AI ke website",
      "nextAction": "Meeting dengan owner Hamasah Internasional: dengar kebutuhan AI, tentukan use-case & estimasi harga",
      "definitionOfDone": "Meeting discovery selesai, scope use-case AI terpetakan, siap kirim penawaran harga",
      "billingMilestone": "Meeting Discovery & Penawaran AI",
      "followUpDeadline": "Meeting Hari Ini"
    }
  ],
  "waitingItems": [
    {
      "id": "w-umi-atiyah",
      "projectId": "p-umi-atiyah",
      "name": "Umi Atiyah",
      "reason": "Pekerjaan sudah selesai 100% - Tinggal pelunasan sisa Rp200.000",
      "value": "Sisa Rp200.000",
      "nextTrigger": "Pelunasan transfer Rp200k masuk rekening",
      "actionToUnblock": "Follow-up santai via WA untuk pelunasan Rp200rb",
      "followUpDate": "Hari ini",
      "status": "Waiting Payment"
    },
    {
      "id": "w-kpi",
      "projectId": "p-komisi-interaksi",
      "name": "Rancangan Komisi Peduli Interaksi (KPI)",
      "reason": "Penawaran harga Rp14.000.000 sudah terkirim - Tinggal tunggu transfer DP sebelum kickoff mulai pengerjaan",
      "value": "Rp14.000.000 (Menunggu DP)",
      "nextTrigger": "Konfirmasi deal & transfer DP dari klien",
      "actionToUnblock": "Standby konfirmasi & follow up berkala proposal Rp14jt",
      "followUpDate": "Hari ini / 1-2 hari",
      "status": "Waiting Payment"
    },
    {
      "id": "w-el-massa",
      "projectId": "p-el-massa",
      "name": "Katalog Web El Massa Tour & Travel",
      "reason": "12 paket ibadah 100% live & fitur aktif - Serah terima laporan proyek & konfirmasi pembayaran final",
      "value": "12 Paket Ibadah Live",
      "nextTrigger": "Konfirmasi serah terima & pembayaran dari pihak El Massa",
      "actionToUnblock": "Kirim laporan komprehensif & konfirmasi jadwal pelunasan proyek",
      "followUpDate": "Hari ini",
      "status": "Waiting Payment"
    },
    {
      "id": "w-ar-ruwad",
      "projectId": "p-ar-ruwad",
      "name": "Ar-Ruwad Logo",
      "reason": "Menunggu pilihan / feedback logo dari client (Sudah dibayar Rp600k)",
      "value": "Rp600.000 (Paid)",
      "nextTrigger": "Pilihan logo final dari client",
      "actionToUnblock": "Touchpoint santai via WhatsApp",
      "followUpDate": "Bulan ini",
      "status": "Waiting Approval"
    }
  ]
};
