import { DaruWorkOSState } from '../types';

export const INITIAL_STATE: DaruWorkOSState = {
  todayPursuit: [
    { id: 'tp-1', project: 'Barbershop Underrated', action: '🏆 BARBERSHOP 100% LUNAS FULL PAYMENT! (+Pelunasan Rp3.000.000 Masuk Mandiri ✓)', isDone: true },
    { id: 'tp-2', project: 'Umi Elly LMS', action: '🚀 KICKOFF SPRINT: DP Termin 1 Rp3.000.000 LUNAS MASUK! Gaspol eksekusi modul LMS Azhariyah', isDone: false },
    { id: 'tp-3', project: 'Zalvice & Laptopbisnis', action: '🎨 2 LOGO DESIGN KELAR! (Zalvice & Laptopbisnis 100% Selesai & Lunas ✓)', isDone: true },
    { id: 'tp-4', project: 'DreamMecca & KAEL Core', action: 'Finishing touch platform DreamMecca & setting config tenant KAEL', isDone: false },
  ],
  quickStats: {
    paidClientActive: 3, // DreamMecca (Lunas lama), Barber (100% Lunas Rp6M), Umi Elly Kickoff (DP Rp3M)
    waitingPaymentKickoff: 0, // All Kickoff payments confirmed!
    maintenanceOpen: 1, // Markaz Fiqih
    salesAndProductActive: 2, // Setting KAEL & Upwork
  },
  financialReport: {
    asOfDate: '2 September 2026',
    totalLiquidBalance: 9892741,
    modeStatus: 'YELLOW MODE — CAUTION',
    hardFloor: 4000000,
    financialDebt: 0,
    projectLiabilityNote: 'SEMUA UTANG DELIVERABLE TUNTAS! (Barber POS Lunas Penuh Rp6M & Umi Elly DP Rp3M Kickoff Aktif). Nol liability design!',
    dropFrom26Aug: 0,
    dropFrom12Aug: 0,
    dropPercentageFrom12Aug: 0,
    accounts: [
      { name: 'Mandiri', balance: 9789529, isLatest: true, lastUpdated: '2 Sep 2026 (Live)', type: 'bank' },
      { name: 'Bank Jago', balance: 30257, isLatest: true, lastUpdated: '2 Sep 2026 (Live)', type: 'bank' },
      { name: 'blu by BCA', balance: 17733, isLatest: true, lastUpdated: '2 Sep 2026 (Live)', type: 'bank' },
      { name: 'LINE Bank', balance: 19336, isLatest: true, lastUpdated: '2 Sep 2026 (Live)', type: 'bank' },
      { name: 'DANA', balance: 27496, isLatest: true, lastUpdated: '2 Sep 2026 (Live)', type: 'ewallet' },
      { name: 'GoPay', balance: 8390, isLatest: true, lastUpdated: '2 Sep 2026 (Live)', type: 'ewallet' },
      { name: 'Cash', balance: 0, isLatest: true, lastUpdated: '2 Sep 2026 (Live)', type: 'cash' },
    ],
    trajectory: [
      { date: '12 Agu', balance: 7810773, note: 'Peak Balance Agustus' },
      { date: '20 Agu', balance: 5885040, note: '-Rp1.92M' },
      { date: '26 Agu', balance: 4755625, note: '-Rp1.13M' },
      { date: '29 Agu', balance: 3945918, note: 'Red Defense Zone (< Rp4M)' },
      { date: '31 Agu', balance: 5333508, note: 'Kewajiban Sep Lunas ✓' },
      { date: '1 Sep', balance: 4130865, note: 'Mandiri Rp4,05M (Investasi Claude Pro 2 Akun • Sisa Di Atas Floor Rp4M)' },
      { date: '2 Sep (Live)', balance: 9892741, note: 'Mandiri Rp9,78M • Total Kas Rp9,89M (Surplus +Rp5,89M di atas Floor!)' },
    ],
    recoveryRoadmap: {
      stage1: 'Rp4.000.000 (Hard Floor Defense Zone — PASSED ✓)',
      stage2: 'Rp4.130.865 (Buffer + 2 Akun Claude Pro — PASSED ✓)',
      stage3: 'Rp7.130.865 (Pelunasan Barber Underrated Rp3M — PASSED ✓)',
      stage4: 'Rp9.892.741 (Live Saldo Kas Aman • Surplus +Rp5,89M di atas Floor!)',
    },
    defenseProtocolRule: 'Saldo likuid Rp9,89M (Surplus masif +Rp5,89M di atas Floor Rp4M). Pemasukan September sudah tembus Rp6.500.000 (65.0% tercapai). Fokus sekarang: Eksekusi sprint modul LMS Umi Elly & scale KAEL SaaS!',
    fixedMonthlyBurn: 3025000,
    estimatedRealBurn: 4500000,
    monthlyIncomeTarget: 10000000,
    runwayDays: 66,
    runwayMonths: 2.2,
    monthlyExpenses: [
      { id: 'exp-1', category: 'Uang istri', estimatedAmount: 1200000, amountText: 'Rp1.200.000 (Lunas Sep ✓)', status: 'Wajib', isFixed: true, notes: 'Nafkah rutin bulanan September 2026 LUNAS terkirim' },
      { id: 'exp-2', category: 'Kewajiban rumah Mesir', estimatedAmount: 500000, amountText: 'Rp500.000 (Lunas Sep ✓)', status: 'Wajib', isFixed: true, notes: 'Kewajiban bulanan Mesir September 2026 LUNAS ✓' },
      { id: 'exp-3', category: 'Internet / kuota', estimatedAmount: 200000, amountText: 'Rp200.000', status: 'Wajib', isFixed: true, notes: 'Koneksi kerja & dev' },
      { id: 'exp-4', category: 'ChatGPT Plus', estimatedAmount: 360000, amountText: 'Rp360.000', status: 'Produktif / langganan aktif', isFixed: true, notes: 'AI Dev workflow' },
      { id: 'exp-5', category: 'Claude Pro (2 Akun)', estimatedAmount: 720000, amountText: '±Rp720.000 (2 Akun Aktif ✓)', status: 'Produktif / langganan aktif', isFixed: true, notes: 'Claude Pro (2 Akun Aktif) untuk AI Coding & High-Volume Reasoning' },
      { id: 'exp-6', category: 'Wavebox', estimatedAmount: 245000, amountText: '±Rp245.000', status: 'Produktif / langganan aktif', isFixed: true, notes: 'Multi-account workspace browser' },
      { id: 'exp-7', category: 'Kebutuhan makan / jajan rumah tangga', estimatedAmount: 'fleksibel', amountText: 'fleksibel (~Rp1.000.000 est.)', status: 'Wajib, fleksibel', isFixed: false, notes: 'Kebutuhan pokok pangan' },
      { id: 'exp-8', category: 'Kebutuhan anak', estimatedAmount: 'fleksibel', amountText: 'fleksibel', status: 'Wajib, fleksibel', isFixed: false, notes: 'Popok, susu & kebutuhan bayi' },
      { id: 'exp-9', category: 'Token / listrik', estimatedAmount: 'fleksibel', amountText: 'fleksibel', status: 'Wajib, fleksibel', isFixed: false, notes: 'Listrik kerja & rumah' },
      { id: 'exp-10', category: 'Transport / kebutuhan harian', estimatedAmount: 'fleksibel', amountText: 'fleksibel', status: 'Wajib, fleksibel', isFixed: false, notes: 'Bensin & mobilitas offline' },
      { id: 'exp-11', category: 'Imunisasi / kesehatan', estimatedAmount: 'tidak selalu bulanan', amountText: 'tidak selalu bulanan', status: 'Wajib, fleksibel', isFixed: false, notes: 'Medis darurat / jadwal vaksin' },
    ],
    transactions: [
      {
        id: 'tx-ifdony-azharuna-sep',
        date: '4 Sep 2026',
        type: 'income',
        amount: 500000,
        accountName: 'Mandiri',
        category: 'Client Payment (Lunas)',
        description: 'Desain Branding & Logo Azharuna (Ustadz Ifdony) (+Rp500.000 Lunas ✓)',
        createdAt: '2026-09-04T10:00:00.000Z'
      },
      {
        id: 'tx-barber-lunas-sep2',
        date: '2 Sep 2026',
        type: 'income',
        amount: 3000000,
        accountName: 'Mandiri',
        category: 'Client Payment (Pelunasan 100%)',
        description: 'Pelunasan 100% Barber POS & Membership System (+Rp3.000.000 Lunas Penuh ✓)',
        createdAt: '2026-09-02T15:45:00.000Z'
      },
      {
        id: 'tx-umi-elly-dp-sep2',
        date: '2 Sep 2026',
        type: 'income',
        amount: 3000000,
        accountName: 'Mandiri',
        category: 'Client Payment (Termin 1 DP)',
        description: 'Termin 1 DP 50% Kickoff LMS Peradaban Islam Azhariyah Umi Elly (+Rp3.000.000 Masuk ✓)',
        createdAt: '2026-09-02T15:50:00.000Z'
      },
      {
        id: 'tx-claude-2acc',
        date: '1 Sep 2026',
        type: 'expense',
        amount: 1202643,
        accountName: 'Mandiri',
        category: 'AI & Operational Tools',
        description: 'Upgrade & Langganan Claude Pro 2 Akun + Pengeluaran Produktif (-Rp1.202.643)',
        createdAt: '2026-09-01T14:41:00.000Z'
      },
      {
        id: 'tx-mandiri-out-35k',
        date: '31 Agu 2026',
        type: 'expense',
        amount: 35000,
        accountName: 'Mandiri',
        category: 'Pengeluaran Harian',
        description: 'Pengeluaran harian rekening Mandiri (-Rp35.000)',
        createdAt: '2026-08-31T13:37:00.000Z'
      },
      {
        id: 'tx-mesir-sep-2026',
        date: '31 Agu 2026',
        type: 'expense',
        amount: 500000,
        accountName: 'Mandiri',
        category: 'Kewajiban Rutin',
        description: 'Kewajiban rumah Mesir bulan September 2026 (Rp500.000 Lunas ✓)',
        createdAt: '2026-08-31T10:55:00.000Z'
      },
      {
        id: 'tx-in-31aug-906k',
        date: '31 Agu 2026',
        type: 'income',
        amount: 906000,
        accountName: 'Mandiri',
        category: 'Client Payment / Revenue',
        description: 'Pemasukan kas masuk rekening Mandiri (+Rp906.000)',
        createdAt: '2026-08-31T09:15:00.000Z'
      },
      {
        id: 'tx-istri-sep-2026',
        date: '31 Agu 2026',
        type: 'expense',
        amount: 1200000,
        accountName: 'Mandiri',
        category: 'Nafkah Keluarga',
        description: 'Kirim uang nafkah istri bulan September 2026 (Rp1.200.000 Lunas ✓)',
        createdAt: '2026-08-31T10:25:00.000Z'
      },
      {
        id: 'tx-barber-dp-1',
        date: '29 Agu 2026',
        type: 'income',
        amount: 3000000,
        accountName: 'Mandiri',
        category: 'Client Payment (DP 50%)',
        description: 'DP 50% Kickoff Barber Membership & Loyalty System (Barber Underrated)',
        createdAt: '2026-08-29T03:52:00.000Z'
      },
      {
        id: 'tx-init-1',
        date: '29 Agu 2026',
        type: 'balance_update',
        amount: 3867000,
        accountName: 'Mandiri',
        category: 'Saldo Live',
        description: 'Update saldo harian rekening Mandiri awal',
        createdAt: '2026-08-29T03:50:00.000Z'
      }
    ]
  },
  todayBlocks: [
    {
      id: 'tb-1',
      blockType: 'Deep Work 1',
      projectName: 'Umi Elly — LMS Azhariyah',
      action: '🚀 KICKOFF SPRINT: DP Rp3M LUNAS! Setup arsitektur modular LMS Azhariyah & struktur materi pembelajaran',
      timeboxMinutes: 90,
      isDone: false,
      rule: 'KICKOFF SPRINT: Bangun pondasi LMS dengan clean UI & arsitektur cepat untuk Umi Elly.'
    },
    {
      id: 'tb-2',
      blockType: 'Deep Work 2',
      projectName: 'Website & Kasir Barber',
      action: '🏆 100% LUNAS FULL PAYMENT! Pelunasan Rp3.000.000 masuk kas Mandiri & serah terima live',
      timeboxMinutes: 60,
      isDone: true,
      rule: 'BARBERSHOP 100% TUNTAS ✓: Selesai penuh dan uang lunas Rp6.000.000 di rekening!'
    },
    {
      id: 'tb-3',
      blockType: 'Growth Block',
      projectName: 'DreamMecca Platform',
      action: 'Finishing touch platform DreamMecca (Lunas dari lama) agar bebas tanggungan deliverable',
      timeboxMinutes: 60,
      isDone: false,
      rule: 'Finishing deliverable platform & serahkan tuntas ke klien.'
    },
    {
      id: 'tb-4',
      blockType: 'Admin/Product',
      projectName: 'Setting KAEL SaaS',
      action: 'Setting config core product, role kasir vs owner & persiapan pilot tenant',
      timeboxMinutes: 45,
      isDone: false,
      rule: 'Fokus setting & fix hal yang mendukung operasional closing pilot.'
    }
  ],
  projects: [
    // 1. CLIENT DELIVERY — Sedang Dikerjakan & Pipeline
    {
      id: 'p-dreammecca',
      name: 'DreamMecca Platform',
      lane: 'client_delivery',
      boardColumn: 'DOING',
      status: 'Doing',
      paymentStatus: 'Paid',
      valueText: 'Lunas dari lama (Finishing Deliverables)',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'P1',
      currentGoal: 'Finishing deliverable platform & landing DreamMecca sampai tuntas',
      nextAction: 'Final touch UI/UX, konten paket umrah & handover ke klien',
      definitionOfDone: 'Platform DreamMecca live & tuntas diserahkan ke klien ✓',
      rule: 'Finishing deliverable yang sudah lunas dari lama agar bebas tanggungan.',
      billingMilestone: 'Paid in Full (Historical)',
      followUpDeadline: 'Finishing malam ini'
    },
    {
      id: 'p-zalvice',
      name: 'Zalvice Logo',
      lane: 'client_delivery',
      boardColumn: 'DONE',
      status: 'Done',
      paymentStatus: 'Paid',
      valueText: 'Bagian dari Rp1,2 jt, sudah dibayar',
      nominalNumeric: 600000,
      paidNumeric: 600000,
      unpaidNumeric: 0,
      priority: 'P1',
      currentGoal: 'Logo Zalvice Bang Edo SELESAI & TUNTAS! (Paket Rp1,2M Lunas)',
      nextAction: 'Handover master assets & mockup ke Bang Edo',
      definitionOfDone: 'Logo Zalvice selesai & diterima klien ✓',
      billingMilestone: 'Paid in Full (Paket Rp1,2M)',
      followUpDeadline: 'Done ✓'
    },
    {
      id: 'p-barber',
      name: 'Barber Membership & Loyalty System (Barber Underrated)',
      lane: 'client_delivery',
      boardColumn: 'DONE',
      status: 'Done',
      paymentStatus: 'Paid',
      valueText: 'Rp6.000.000 (100% LUNAS FULL PAYMENT ✓)',
      nominalNumeric: 6000000,
      paidNumeric: 6000000,
      unpaidNumeric: 0,
      priority: 'P1',
      currentGoal: '100% TUNTAS & LUNAS FULL PAYMENT! (DP Rp3M + Pelunasan Rp3M Masuk Kas Mandiri)',
      nextAction: 'Dampingi operasional opening & maintenance bila ada request minor',
      definitionOfDone: 'Website & POS Kasir Barber live, serah terima tuntas, uang lunas Rp6.000.000 ✓',
      rule: 'Barbershop 100% LUNAS & tuntas.',
      billingMilestone: '100% Paid in Full (Rp6.000.000 Lunas ✓)',
      followUpDeadline: 'Done ✓'
    },
    {
      id: 'p-kael-product',
      name: 'Setting KAEL (Core Product)',
      lane: 'own_product',
      boardColumn: 'DOING',
      status: 'Doing',
      paymentStatus: 'Recurring/Pipeline',
      valueText: 'Core SaaS Asset (Active Setup)',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'P2',
      currentGoal: 'Setting konfigurasi core product & fix blocker demo/closing',
      nextAction: 'Setting role kasir vs owner, staff sync, self-order double pay, QRIS static flow & tenant demo',
      definitionOfDone: 'Semua setting dan flow kasir/owner berjalan stabil',
      rule: 'Jangan nambah fitur random! Fokus setting hal yang langsung mendukung penjualan.',
      billingMilestone: 'Product Stability & Pilot Ready',
      followUpDeadline: 'Selesai setting hari ini'
    },
    {
      id: 'p-laptopbisnis',
      name: 'Laptopbisnis Logo',
      lane: 'client_delivery',
      boardColumn: 'DONE',
      status: 'Done',
      paymentStatus: 'Paid',
      valueText: 'Bagian dari Rp1,2 jt, sudah dibayar',
      nominalNumeric: 600000,
      paidNumeric: 600000,
      unpaidNumeric: 0,
      priority: 'P1',
      currentGoal: 'Logo Laptopbisnis SELESAI & TUNTAS! (Bagian dari Paket Rp1,2M Lunas)',
      nextAction: 'Handover master assets & mockup ke klien',
      definitionOfDone: 'Logo Laptopbisnis selesai & diterima klien ✓',
      rule: 'Queue: Eksekusi segera setelah Zalvice tuntas',
      billingMilestone: 'Paid in Full',
      followUpDeadline: 'Done ✓'
    },
    {
      id: 'p-ifdony-azharuna',
      name: 'Logo Azharuna (Ustadz Ifdony)',
      lane: 'client_delivery',
      boardColumn: 'DONE',
      status: 'Done',
      paymentStatus: 'Paid',
      valueText: 'Rp500.000 (Lunas September 2026 ✓)',
      nominalNumeric: 500000,
      paidNumeric: 500000,
      unpaidNumeric: 0,
      priority: 'P2',
      currentGoal: 'Desain Branding & Logo Azharuna Tuntas & Lunas',
      nextAction: 'Handover master vector AI, EPS, SVG, PNG & PDF',
      definitionOfDone: 'Master file logo diserahkan & pembayaran Rp500.000 lunas ✓',
      billingMilestone: '100% Paid in Full (Rp500.000 Lunas)',
      followUpDeadline: 'Done ✓'
    },
    {
      id: 'p-umi-elly',
      name: 'Umi Elly — LMS Peradaban Islam Azhariyah',
      lane: 'client_delivery',
      boardColumn: 'DOING',
      status: 'Doing',
      paymentStatus: 'Partial',
      valueText: 'Deal Rp7.000.000 (Termin 1: DP Rp3M LUNAS ✓ • Sisa Termin 2 & 3 Rp4M)',
      nominalNumeric: 7000000,
      paidNumeric: 3000000,
      unpaidNumeric: 4000000,
      priority: 'P1',
      currentGoal: 'DP Termin 1 Rp3.000.000 SUDAH MASUK! 🚀 Gaspol kickoff sprint pengerjaan modul lengkap LMS Azhariyah',
      nextAction: 'Eksekusi modul LMS Peradaban Islam Azhariyah & struktur materi pembelajaran',
      definitionOfDone: 'Modul LMS Peradaban Islam Azhariyah live & deploy',
      rule: 'DP Rp3M sudah masuk kas: Gaspol sprint pengerjaan modul lengkap dengan standar kualitas tinggi.',
      billingMilestone: 'Termin 1: DP Rp3.000.000 (LUNAS ✓) • Termin 2: Rp2.000.000 • Termin 3: Rp2.000.000',
      followUpDeadline: 'Sprint Kickoff Aktif'
    },
    {
      id: 'p-el-massa',
      name: 'El Massa',
      lane: 'client_delivery',
      boardColumn: 'WAITING',
      status: 'Waiting Payment',
      paymentStatus: 'Waiting Payment',
      valueText: 'Belum dibayar (Follow-up)',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'P2',
      currentGoal: 'Tagih deliverables yang sudah selesai',
      nextAction: 'Follow-up pembayaran untuk deliverables yang sudah selesai; jangan tambah scope sebelum status jelas',
      definitionOfDone: 'Status pembayaran clear & lunas',
      rule: 'Jangan tambah scope sebelum pembayaran deliverables sebelumnya jelas.',
      billingMilestone: 'Invoice Outstanding Deliverables',
      followUpDeadline: 'Kirim reminder invoice'
    },
    {
      id: 'p-ar-ruwad',
      name: 'Ar-Ruwad Logo',
      lane: 'client_delivery',
      boardColumn: 'WAITING',
      status: 'Waiting Approval',
      paymentStatus: 'Paid',
      valueText: 'Sudah dibayar lama Rp600k',
      nominalNumeric: 600000,
      paidNumeric: 600000,
      unpaidNumeric: 0,
      priority: 'P2',
      currentGoal: 'Menunggu respon pilihan logo',
      nextAction: 'Tunggu pilihan / feedback logo dari client',
      definitionOfDone: 'Client memilih salah satu konsep logo final',
      billingMilestone: 'Paid in Advance (Rp600k)',
      followUpDeadline: 'Touchpoint santai via WA'
    },
    {
      id: 'p-ibrahim-visa',
      name: 'Ibrahim Nawawi (Visa Student Kairo)',
      lane: 'client_delivery',
      boardColumn: 'WAITING',
      status: 'Waiting Payment',
      paymentStatus: 'Waiting Payment',
      valueText: 'Rp1.100.000 (Invoice Terbit)',
      nominalNumeric: 1100000,
      paidNumeric: 0,
      unpaidNumeric: 1100000,
      priority: 'P2',
      currentGoal: 'Pengurusan Visa Entry Student Kairo',
      nextAction: 'Follow-up pembayaran & verifikasi kelengkapan dokumen (Paspor, Pasfoto, Tadaruj Dirasi)',
      definitionOfDone: 'Pembayaran Rp1.100.000 masuk & proses kedutaan berjalan',
      billingMilestone: 'Invoice INV/VES/2026/016 (Rp1.100.000)',
      followUpDeadline: 'Follow-up invoice via WA'
    },

    // 2. MAINTENANCE
    {
      id: 'p-markaz',
      name: 'Markaz Fiqih',
      lane: 'maintenance',
      boardColumn: 'QUEUE',
      status: 'Queue',
      paymentStatus: 'Free',
      valueText: 'Free Maintenance',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'P3',
      currentGoal: 'Cuma beresin issue yang bener-bener urgent',
      nextAction: 'List bug → pilih maksimal 1–2 issue urgent → timebox 1–2 jam',
      definitionOfDone: 'Max 2 bug urgent tuntas tanpa merembet ke modul lain',
      rule: 'Markaz nggak boleh makan deep-work slot kerjaan berbayar.',
      timebox: '1–2 jam per sesi',
      billingMilestone: 'Non-billable (Free)',
      followUpDeadline: 'Bila ada waktu luang setelah paid tasks'
    },

    // 3. BUSINESS DEVELOPMENT / SALES
    {
      id: 'p-kael-marketing',
      name: 'KAEL — Offline Marketing',
      lane: 'bizdev',
      boardColumn: 'DOING',
      status: 'Doing',
      paymentStatus: 'Recurring/Pipeline',
      valueText: '3-5 Pilot Customer Goal',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'P2',
      currentGoal: 'Cari customer nyata & kumpulkan feedback lapangan',
      nextAction: 'Bawa brosur, demo langsung ke UMKM (Review/POS), follow-up yang sudah pernah lihat demo, cari 3-5 pilot customer pertama',
      definitionOfDone: '3-5 pilot customer onboard & feedback tercatat',
      rule: 'Fokus tawarkan solusi nyata (Review/POS) sesuai kebutuhan bisnis mereka.',
      billingMilestone: 'SaaS Setup Fee / Monthly Subscription',
      followUpDeadline: '1 outlet hari ini'
    },
    {
      id: 'p-upwork',
      name: 'Upwork Global Pipeline',
      lane: 'bizdev',
      boardColumn: 'QUEUE',
      status: 'Queue',
      paymentStatus: 'Recurring/Pipeline',
      valueText: 'USD High-Ticket Pipeline',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'P2',
      currentGoal: 'Jaga peluang cashflow baru tanpa mengganggu delivery',
      nextAction: 'Apply 3–5 job berkualitas (Next.js, React, Supabase, dashboard, internal tools, POS, landing, bug fixing)',
      definitionOfDone: '3 proposal spesifik terkirim',
      rule: 'Bukan spam proposal. Jangan buang Connects asal-asalan.',
      billingMilestone: 'Hourly / Fixed Price USD',
      followUpDeadline: 'Malam ini saat rilis job baru'
    },
    {
      id: 'p-watra',
      name: 'Al Madroj / Watra',
      lane: 'bizdev',
      boardColumn: 'WAITING',
      status: 'Discovery / Lead',
      paymentStatus: 'Expected',
      valueText: 'Website/Platform Kelas LMS',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'P3',
      currentGoal: 'Gali scope yang sebenarnya untuk platform kelas/LMS',
      nextAction: 'Follow-up dan gali scope yang sebenarnya',
      definitionOfDone: 'Scope proposal terkirim',
      billingMilestone: 'Proposal Acceptance',
      followUpDeadline: 'Follow-up chat'
    },

    // 4. OWN PRODUCT — KAEL Demo by Industry
    {
      id: 'p-kael-demo-percetakan',
      name: 'KAEL Demo by Industry (Percetakan)',
      lane: 'own_product',
      boardColumn: 'QUEUE',
      status: 'Queue',
      paymentStatus: 'Recurring/Pipeline',
      valueText: 'Industry-Specific Demo Flow',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'P3',
      currentGoal: 'Bikin demo relate langsung ke bisnis percetakan (feedback nyata pemilik percetakan)',
      nextAction: 'Setup dummy data + flow yang relevan untuk Demo Percetakan',
      definitionOfDone: 'Tenant demo percetakan siap dipresentasikan',
      rule: 'Engine tetap sama, yang berubah mainly dummy data + flow yang relevan.',
      billingMilestone: 'Conversion Rate Multiplier',
      followUpDeadline: 'Siap untuk demo minggu ini'
    },

    // 5. ONGOING BUSINESS / OPERATIONS
    {
      id: 'p-temantiket',
      name: 'Temantiket',
      lane: 'operations',
      boardColumn: 'WAITING',
      status: 'Ongoing',
      paymentStatus: 'Recurring/Pipeline',
      valueText: 'Business Operations Asset',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'P3',
      currentGoal: 'Jaga operasional tanpa memakan daily deep work slot',
      nextAction: 'Eksekusi cuma jika ada order konkret / customer follow-up / operational issue',
      definitionOfDone: 'Operasional harian lancar',
      rule: 'Jangan masuk daily deep-work kecuali ada order, customer follow-up, issue, atau peluang revenue konkret.',
      billingMilestone: 'Operations Cashflow',
      followUpDeadline: 'As orders arrive'
    },

    // 6. PARKING LOT / LOST DEALS
    {
      id: 'p-bedug',
      name: 'Bedug.net',
      lane: 'parking_lot',
      boardColumn: 'PARKED',
      status: 'Parked',
      paymentStatus: 'Parked',
      valueText: 'Lost / Cancelled (Rp2,2 jt)',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'PARKED',
      currentGoal: 'Lost Deal',
      nextAction: 'Archived (Deal dibatalkan / tidak lanjut)',
      rule: 'Tidak ada alokasi waktu.'
    },
    {
      id: 'p-teh-umi',
      name: 'Teh Umi — E-reader Basic',
      lane: 'parking_lot',
      boardColumn: 'PARKED',
      status: 'Parked',
      paymentStatus: 'Parked',
      valueText: 'Lost / Dropped (Rp300k)',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'PARKED',
      currentGoal: 'Lost Project',
      nextAction: 'Archived (Cicilan dropped / tidak lanjut build)',
      rule: 'Tidak ada alokasi waktu.'
    },
    {
      id: 'p-nemsyi',
      name: 'Nemsyi',
      lane: 'parking_lot',
      boardColumn: 'PARKED',
      status: 'Parked',
      paymentStatus: 'Parked',
      valueText: 'Paused Project',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'PARKED',
      currentGoal: 'Paused',
      nextAction: 'Jangan sentuh sebelum fokus utama selesai',
      rule: 'Jangan rebutan perhatian dengan kerjaan aktif sekarang.'
    },
    {
      id: 'p-qohiroh',
      name: 'Qohiroh',
      lane: 'parking_lot',
      boardColumn: 'PARKED',
      status: 'Parked',
      paymentStatus: 'Parked',
      valueText: 'Lost / Dormant',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'PARKED',
      currentGoal: 'Dormant',
      nextAction: 'Archived',
      rule: 'Tidak ada alokasi waktu.'
    },
    {
      id: 'p-saudi-addon',
      name: 'Saudi Add-on',
      lane: 'parking_lot',
      boardColumn: 'PARKED',
      status: 'Parked',
      paymentStatus: 'Parked',
      valueText: 'Dormant / Lost',
      nominalNumeric: 0,
      paidNumeric: 0,
      unpaidNumeric: 0,
      priority: 'PARKED',
      currentGoal: 'Dormant',
      nextAction: 'Archived',
      rule: 'Tidak ada alokasi waktu.'
    }
  ],
  waitingItems: [
    {
      id: 'w-umi-elly',
      name: 'Umi Elly — LMS Peradaban Islam Azhariyah',
      reason: 'Demo prototype sudah dikirim — Menunggu feedback & transfer Termin 1 DP Rp3.000.000 (Deal Rp7M)',
      value: 'Deal Rp7.000.000 (DP Rp3jt OTW)',
      nextTrigger: 'Transfer termin 1 (Rp3jt) masuk',
      actionToUnblock: 'Konfirmasi feedback demo & tanggal transfer termin 1',
      followUpDate: 'Hari ini / Besok',
      status: 'Waiting Payment'
    },
    {
      id: 'w-el-massa',
      name: 'El Massa',
      reason: 'Menunggu pembayaran deliverables yang sudah selesai dikerjakan',
      value: 'Invoice Outstanding',
      nextTrigger: 'Pembayaran deliverables selesai',
      actionToUnblock: 'Follow-up status pembayaran, jangan tambah scope baru',
      followUpDate: 'Hari ini',
      status: 'Waiting Payment'
    },
    {
      id: 'w-ar-ruwad',
      name: 'Ar-Ruwad Logo',
      reason: 'Menunggu pilihan/feedback logo dari client (Sudah dibayar Rp600k)',
      value: 'Rp600.000 (Paid)',
      nextTrigger: 'Pilihan logo final dari client',
      actionToUnblock: 'Touchpoint santai via WhatsApp',
      followUpDate: 'Bulan ini',
      status: 'Waiting Approval'
    },
    {
      id: 'w-watra',
      name: 'Al Madroj / Watra',
      reason: 'Menunggu eksplorasi scope kebutuhan website/LMS kelas',
      value: 'Lead Pipeline',
      nextTrigger: 'Meeting/Chat discovery scope',
      actionToUnblock: 'Follow-up dan gali scope yang sebenarnya',
      followUpDate: 'Minggu ini',
      status: 'Discovery'
    }
  ]
};
